inherit_from: ../hitobito/.rubocop.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - Rakefile
    - Guardfile
    - db/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - spec/**/*
    - test/**/*