# Settings relevant for the jubla wagon
# Overrides settings from the main application
application:
  name: jubla.db
  footer:
    logo_image: logo_jubla.png
    logo_url: http://www.jubla.ch
    links:
      "Fragen und Anregungen": http://feedback.jubla.ch
      Hilfe: http://jubla.ch/datenbank

census:
  default_finish_month: 10
  default_finish_day: 31

email:
  # Sender for all emails sent by the application
  sender: <%= "jubla.db <noreply@#{ENV['RAILS_HOST_NAME'].presence || 'localhost'}>" %>

  # If mass emails are sent, this recipient is used in the to field,
  # while the actual recipients go in the bcc field.
  mass_recipient: noreply@db.jubla.ch